using Fohjin.DDD.ApiClient;
using Microsoft.AspNetCore.Mvc.Testing;

namespace Test.Fohjin.DDD.ApiClient;

// Phase 2 exit criteria: a client generated by NSwag from Fohjin.DDD.WebApi's OpenAPI document
// can create and read a client through the API. WebApplicationFactory<Program> hosts the real
// app in-memory (no live server/port needed).
//
// ApplicationBootStrapper (Fohjin.DDD.BankApplication.Core) migrates the domain-event and
// reporting SQLite databases at Path.GetFullPath("domainDataBase.db3"/"reportingDataBase.db3")
// - i.e. relative to the process's current directory, ignoring IConfiguration entirely - while
// the runtime DbContext factories resolve their connection string through configuration. Those
// two happen to agree in normal (dev) usage because appsettings.json points at the same relative
// filenames, but it means a config-only override (e.g. via ConfigureAppConfiguration) would make
// the bootstrapper migrate one file while the app queries another. So isolation here works by
// switching the process's current directory to a fresh temp folder instead, which both paths
// resolve against consistently. That makes this test unsafe to run in parallel with anything
// else that depends on the process CWD - hence no [assembly: Parallelize] in this project.
[TestClass]
[TestCategory("integration")]
public class CreateAndReadClientThroughGeneratedApiClientTest
{
    private string _originalDirectory = null!;
    private string _tempDirectory = null!;
    private WebApplicationFactory<Program> _factory = null!;
    private HttpClient _httpClient = null!;
    private FohjinApiClient _client = null!;

    [TestInitialize]
    public void Setup()
    {
        _originalDirectory = Directory.GetCurrentDirectory();
        _tempDirectory = Path.Combine(Path.GetTempPath(), $"Fohjin.DDD.ApiClient.Tests_{Guid.NewGuid()}");
        Directory.CreateDirectory(_tempDirectory);
        Directory.SetCurrentDirectory(_tempDirectory);

        _factory = new WebApplicationFactory<Program>();

        _httpClient = _factory.CreateClient();
        _client = new FohjinApiClient(_httpClient) { BaseUrl = _httpClient.BaseAddress!.ToString() };
    }

    [TestCleanup]
    public void TearDown()
    {
        _httpClient.Dispose();
        _factory.Dispose();
        Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools(); // else the temp dir's .db3 files stay locked
        Directory.SetCurrentDirectory(_originalDirectory);
        Directory.Delete(_tempDirectory, recursive: true);
    }

    [TestMethod]
    public async Task Generated_client_can_create_a_client_and_read_it_back()
    {
        await _client.CreateClientAsync(new CreateClientRequest
        {
            ClientName = "Mark Nijhof",
            Street = "Welhavens gate",
            StreetNumber = "49b",
            PostalCode = "5006",
            City = "Bergen",
            PhoneNumber = "95009937",
        });

        // DirectBus.CommitAsync() is fire-and-forget (docs/07-messaging-bus.md), so the new
        // client shows up in the read model asynchronously - poll briefly rather than assume
        // it's there the instant CreateClientAsync returns.
        ClientReport? created = null;
        for (var attempt = 0; attempt < 30 && created is null; attempt++)
        {
            await Task.Delay(100);
            created = (await _client.GetClientsAsync()).FirstOrDefault(c => c.Name == "Mark Nijhof");
        }

        Assert.IsNotNull(created, "the created client did not appear in GetClientsAsync within the retry window");

        var fetched = await _client.GetClientByIdAsync(created!.Id);

        Assert.AreEqual("Mark Nijhof", fetched.Name);
    }
}
