<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>aef806dc-7008-40a0-a2d8-4e1852a92951</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fohjin.DDD.Sts\Fohjin.DDD.Sts.csproj" />
    <ProjectReference Include="..\Fohjin.DDD.WebApi\Fohjin.DDD.WebApi.csproj" />
  </ItemGroup>

</Project>
