using Fohjin.DDD.ApiClient;

namespace Fohjin.DDD.ApiClient.Tests;

// Phase 2 exit criteria: a client generated by NSwag from Fohjin.DDD.WebApi's OpenAPI document
// can create and read a client through the API.
[TestClass]
[TestCategory("integration")]
public class CreateAndReadClientThroughGeneratedApiClientTest : WebApiIntegrationTestFixture
{
    private FohjinApiClient _client = null!;

    [TestInitialize]
    public void Setup()
    {
        _client = new FohjinApiClient(HttpClient) { BaseUrl = HttpClient.BaseAddress!.ToString() };
    }

    [TestMethod]
    public async Task Generated_client_can_create_a_client_and_read_it_back()
    {
        await _client.CreateClientAsync(new CreateClientRequest
        {
            ClientName = "Mark Nijhof",
            Street = "Welhavens gate",
            StreetNumber = "49b",
            PostalCode = "5006",
            City = "Bergen",
            PhoneNumber = "95009937",
        });

        // DirectBus.CommitAsync() is fire-and-forget (docs/07-messaging-bus.md), so the new
        // client shows up in the read model asynchronously - poll briefly rather than assume
        // it's there the instant CreateClientAsync returns.
        ClientReport? created = null;
        for (var attempt = 0; attempt < 30 && created is null; attempt++)
        {
            await Task.Delay(100);
            created = (await _client.GetClientsAsync()).FirstOrDefault(c => c.Name == "Mark Nijhof");
        }

        Assert.IsNotNull(created, "the created client did not appear in GetClientsAsync within the retry window");

        var fetched = await _client.GetClientByIdAsync(created!.Id);

        Assert.AreEqual("Mark Nijhof", fetched.Name);
    }
}
