// <auto-generated />
using System;
using Fohjin.DDD.EventStore.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fohjin.DDD.EventStore.SQLite.Migrations
{
    [DbContext(typeof(DomainEventStoreDbContext))]
    [Migration("20260729001125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fohjin.DDD.EventStore.SQLite.Entities.EventProviderEntity", b =>
                {
                    b.Property<Guid>("EventProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("EventProviderId");

                    b.ToTable("EventProviders", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.EventStore.SQLite.Entities.EventRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Event")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("EventProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventProviderId", "Version");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.EventStore.SQLite.Entities.SnapShotEntity", b =>
                {
                    b.Property<Guid>("EventProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("SnapShot")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("EventProviderId");

                    b.ToTable("SnapShots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
