// <auto-generated />
using System;
using Fohjin.DDD.EventStore.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fohjin.DDD.EventStore.SqlServer.Migrations
{
    [DbContext(typeof(DomainEventStoreDbContext))]
    partial class DomainEventStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fohjin.DDD.EventStore.SqlServer.Entities.EventProviderEntity", b =>
                {
                    b.Property<Guid>("EventProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("EventProviderId");

                    b.ToTable("EventProviders", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.EventStore.SqlServer.Entities.EventRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Event")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("EventProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventProviderId", "Version");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.EventStore.SqlServer.Entities.SnapShotEntity", b =>
                {
                    b.Property<Guid>("EventProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("SnapShot")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("EventProviderId");

                    b.ToTable("SnapShots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
