//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming


export class FohjinApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://127.0.0.1:5320/";
    }

    /**
     * @return Accepted
     */
    createClient(body: CreateClientRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateClient(_response);
        });
    }

    protected processCreateClient(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getClients(): Promise<ClientReport[]> {
        let url_ = this.baseUrl + "/api/clients";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClients(_response);
        });
    }

    protected processGetClients(response: Response): Promise<ClientReport[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClientReport.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport[]>(null as any);
    }

    /**
     * @return OK
     */
    getClientById(id: string): Promise<ClientReport> {
        let url_ = this.baseUrl + "/api/clients/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClientById(_response);
        });
    }

    protected processGetClientById(response: Response): Promise<ClientReport> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClientReport.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport>(null as any);
    }

    /**
     * @return OK
     */
    getClientDetailsById(id: string): Promise<ClientDetailsReport> {
        let url_ = this.baseUrl + "/api/clients/{id}/details";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClientDetailsById(_response);
        });
    }

    protected processGetClientDetailsById(response: Response): Promise<ClientDetailsReport> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClientDetailsReport.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientDetailsReport>(null as any);
    }

    /**
     * @return Accepted
     */
    changeClientName(id: string, body: ChangeClientNameRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/name";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeClientName(_response);
        });
    }

    protected processChangeClientName(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    changeClientAddress(id: string, body: ClientIsMovingRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/address";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeClientAddress(_response);
        });
    }

    protected processChangeClientAddress(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    changeClientPhoneNumber(id: string, body: ChangeClientPhoneNumberRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/phone-number";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeClientPhoneNumber(_response);
        });
    }

    protected processChangeClientPhoneNumber(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    openNewAccountForClient(id: string, body: OpenNewAccountForClientRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/accounts";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOpenNewAccountForClient(_response);
        });
    }

    protected processOpenNewAccountForClient(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    queryClients(): Promise<ClientReport[]> {
        let url_ = this.baseUrl + "/odata/Clients";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processQueryClients(_response);
        });
    }

    protected processQueryClients(response: Response): Promise<ClientReport[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClientReport.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result400 = resultData400 !== undefined ? resultData400 : null as any;
    
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport[]>(null as any);
    }

    streamEvents(): Promise<void> {
        let url_ = this.baseUrl + "/api/events";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamEvents(_response);
        });
    }

    protected processStreamEvents(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result400 = resultData400 !== undefined ? resultData400 : null as any;
    
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class AccountReport implements IAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IAccountReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.clientDetailsReportId = _data["clientDetailsReportId"];
            this.accountName = _data["accountName"];
            this.accountNumber = _data["accountNumber"];
        }
    }

    static fromJS(data: any): AccountReport {
        data = typeof data === 'object' ? data : {};
        let result = new AccountReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["clientDetailsReportId"] = this.clientDetailsReportId;
        data["accountName"] = this.accountName;
        data["accountNumber"] = this.accountNumber;
        return data;
    }
}

export interface IAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;
}

export class ChangeClientNameRequest implements IChangeClientNameRequest {
    clientName!: string | undefined;

    [key: string]: any;

    constructor(data?: IChangeClientNameRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.clientName = _data["clientName"];
        }
    }

    static fromJS(data: any): ChangeClientNameRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ChangeClientNameRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["clientName"] = this.clientName;
        return data;
    }
}

export interface IChangeClientNameRequest {
    clientName: string | undefined;

    [key: string]: any;
}

export class ChangeClientPhoneNumberRequest implements IChangeClientPhoneNumberRequest {
    phoneNumber!: string | undefined;

    [key: string]: any;

    constructor(data?: IChangeClientPhoneNumberRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.phoneNumber = _data["phoneNumber"];
        }
    }

    static fromJS(data: any): ChangeClientPhoneNumberRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ChangeClientPhoneNumberRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["phoneNumber"] = this.phoneNumber;
        return data;
    }
}

export interface IChangeClientPhoneNumberRequest {
    phoneNumber: string | undefined;

    [key: string]: any;
}

export class ClientDetailsReport implements IClientDetailsReport {
    id?: string;
    accounts?: AccountReport[];
    closedAccounts?: ClosedAccountReport[];
    clientName?: string | undefined;
    street?: string | undefined;
    streetNumber?: string | undefined;
    postalCode?: string | undefined;
    city?: string | undefined;
    phoneNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IClientDetailsReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            if (Array.isArray(_data["accounts"])) {
                this.accounts = [] as any;
                for (let item of _data["accounts"])
                    this.accounts!.push(AccountReport.fromJS(item));
            }
            if (Array.isArray(_data["closedAccounts"])) {
                this.closedAccounts = [] as any;
                for (let item of _data["closedAccounts"])
                    this.closedAccounts!.push(ClosedAccountReport.fromJS(item));
            }
            this.clientName = _data["clientName"];
            this.street = _data["street"];
            this.streetNumber = _data["streetNumber"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
            this.phoneNumber = _data["phoneNumber"];
        }
    }

    static fromJS(data: any): ClientDetailsReport {
        data = typeof data === 'object' ? data : {};
        let result = new ClientDetailsReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        if (Array.isArray(this.accounts)) {
            data["accounts"] = [];
            for (let item of this.accounts)
                data["accounts"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.closedAccounts)) {
            data["closedAccounts"] = [];
            for (let item of this.closedAccounts)
                data["closedAccounts"].push(item ? item.toJSON() : undefined as any);
        }
        data["clientName"] = this.clientName;
        data["street"] = this.street;
        data["streetNumber"] = this.streetNumber;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        data["phoneNumber"] = this.phoneNumber;
        return data;
    }
}

export interface IClientDetailsReport {
    id?: string;
    accounts?: AccountReport[];
    closedAccounts?: ClosedAccountReport[];
    clientName?: string | undefined;
    street?: string | undefined;
    streetNumber?: string | undefined;
    postalCode?: string | undefined;
    city?: string | undefined;
    phoneNumber?: string | undefined;

    [key: string]: any;
}

export class ClientIsMovingRequest implements IClientIsMovingRequest {
    street!: string | undefined;
    streetNumber!: string | undefined;
    postalCode!: string | undefined;
    city!: string | undefined;

    [key: string]: any;

    constructor(data?: IClientIsMovingRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.street = _data["street"];
            this.streetNumber = _data["streetNumber"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
        }
    }

    static fromJS(data: any): ClientIsMovingRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ClientIsMovingRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["street"] = this.street;
        data["streetNumber"] = this.streetNumber;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        return data;
    }
}

export interface IClientIsMovingRequest {
    street: string | undefined;
    streetNumber: string | undefined;
    postalCode: string | undefined;
    city: string | undefined;

    [key: string]: any;
}

export class ClientReport implements IClientReport {
    id?: string;
    name?: string | undefined;

    [key: string]: any;

    constructor(data?: IClientReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ClientReport {
        data = typeof data === 'object' ? data : {};
        let result = new ClientReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IClientReport {
    id?: string;
    name?: string | undefined;

    [key: string]: any;
}

export class ClosedAccountReport implements IClosedAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IClosedAccountReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.clientDetailsReportId = _data["clientDetailsReportId"];
            this.accountName = _data["accountName"];
            this.accountNumber = _data["accountNumber"];
        }
    }

    static fromJS(data: any): ClosedAccountReport {
        data = typeof data === 'object' ? data : {};
        let result = new ClosedAccountReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["clientDetailsReportId"] = this.clientDetailsReportId;
        data["accountName"] = this.accountName;
        data["accountNumber"] = this.accountNumber;
        return data;
    }
}

export interface IClosedAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;
}

export class CreateClientRequest implements ICreateClientRequest {
    clientName!: string | undefined;
    street!: string | undefined;
    streetNumber!: string | undefined;
    postalCode!: string | undefined;
    city!: string | undefined;
    phoneNumber!: string | undefined;

    [key: string]: any;

    constructor(data?: ICreateClientRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.clientName = _data["clientName"];
            this.street = _data["street"];
            this.streetNumber = _data["streetNumber"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
            this.phoneNumber = _data["phoneNumber"];
        }
    }

    static fromJS(data: any): CreateClientRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateClientRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["clientName"] = this.clientName;
        data["street"] = this.street;
        data["streetNumber"] = this.streetNumber;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        data["phoneNumber"] = this.phoneNumber;
        return data;
    }
}

export interface ICreateClientRequest {
    clientName: string | undefined;
    street: string | undefined;
    streetNumber: string | undefined;
    postalCode: string | undefined;
    city: string | undefined;
    phoneNumber: string | undefined;

    [key: string]: any;
}

export class OpenNewAccountForClientRequest implements IOpenNewAccountForClientRequest {
    accountName!: string | undefined;

    [key: string]: any;

    constructor(data?: IOpenNewAccountForClientRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.accountName = _data["accountName"];
        }
    }

    static fromJS(data: any): OpenNewAccountForClientRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OpenNewAccountForClientRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["accountName"] = this.accountName;
        return data;
    }
}

export interface IOpenNewAccountForClientRequest {
    accountName: string | undefined;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

