//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming


export class FohjinApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://127.0.0.1:5320/";
    }

    /**
     * @return Accepted
     */
    createClient(body: CreateClientRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateClient(_response);
        });
    }

    protected processCreateClient(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getClients(): Promise<ClientReport[]> {
        let url_ = this.baseUrl + "/api/clients";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClients(_response);
        });
    }

    protected processGetClients(response: Response): Promise<ClientReport[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClientReport.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport[]>(null as any);
    }

    /**
     * @return OK
     */
    getClientById(id: string): Promise<ClientReport> {
        let url_ = this.baseUrl + "/api/clients/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClientById(_response);
        });
    }

    protected processGetClientById(response: Response): Promise<ClientReport> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClientReport.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport>(null as any);
    }

    /**
     * @return OK
     */
    getClientDetailsById(id: string): Promise<ClientDetailsReport> {
        let url_ = this.baseUrl + "/api/clients/{id}/details";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetClientDetailsById(_response);
        });
    }

    protected processGetClientDetailsById(response: Response): Promise<ClientDetailsReport> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClientDetailsReport.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientDetailsReport>(null as any);
    }

    /**
     * @return Accepted
     */
    changeClientName(id: string, body: ChangeClientNameRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/name";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeClientName(_response);
        });
    }

    protected processChangeClientName(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    changeClientAddress(id: string, body: ClientIsMovingRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/address";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeClientAddress(_response);
        });
    }

    protected processChangeClientAddress(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    changeClientPhoneNumber(id: string, body: ChangeClientPhoneNumberRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/phone-number";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeClientPhoneNumber(_response);
        });
    }

    protected processChangeClientPhoneNumber(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    openNewAccountForClient(id: string, body: OpenNewAccountForClientRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/accounts";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processOpenNewAccountForClient(_response);
        });
    }

    protected processOpenNewAccountForClient(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    assignNewBankCard(id: string, body: AssignNewBankCardRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/bank-cards";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAssignNewBankCard(_response);
        });
    }

    protected processAssignNewBankCard(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    cancelBankCard(id: string, bankCardId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/bank-cards/{bankCardId}/cancel";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (bankCardId === undefined || bankCardId === null)
            throw new globalThis.Error("The parameter 'bankCardId' must be defined.");
        url_ = url_.replace("{bankCardId}", encodeURIComponent("" + bankCardId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCancelBankCard(_response);
        });
    }

    protected processCancelBankCard(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    reportStolenBankCard(id: string, bankCardId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/clients/{id}/bank-cards/{bankCardId}/report-stolen";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (bankCardId === undefined || bankCardId === null)
            throw new globalThis.Error("The parameter 'bankCardId' must be defined.");
        url_ = url_.replace("{bankCardId}", encodeURIComponent("" + bankCardId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReportStolenBankCard(_response);
        });
    }

    protected processReportStolenBankCard(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getAccounts(): Promise<AccountReport[]> {
        let url_ = this.baseUrl + "/api/accounts";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAccounts(_response);
        });
    }

    protected processGetAccounts(response: Response): Promise<AccountReport[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(AccountReport.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccountReport[]>(null as any);
    }

    /**
     * @return OK
     */
    getAccountDetailsById(id: string): Promise<AccountDetailsReport> {
        let url_ = this.baseUrl + "/api/accounts/{id}/details";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAccountDetailsById(_response);
        });
    }

    protected processGetAccountDetailsById(response: Response): Promise<AccountDetailsReport> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AccountDetailsReport.fromJS(resultData200);
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("Not Found", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AccountDetailsReport>(null as any);
    }

    /**
     * @return Accepted
     */
    changeAccountName(id: string, body: ChangeAccountNameRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/accounts/{id}/name";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processChangeAccountName(_response);
        });
    }

    protected processChangeAccountName(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    depositCash(id: string, body: DepositCashRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/accounts/{id}/deposit";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDepositCash(_response);
        });
    }

    protected processDepositCash(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    withdrawalCash(id: string, body: WithdrawalCashRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/accounts/{id}/withdrawal";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processWithdrawalCash(_response);
        });
    }

    protected processWithdrawalCash(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    sendMoneyTransfer(id: string, body: SendMoneyTransferRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/accounts/{id}/transfer";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSendMoneyTransfer(_response);
        });
    }

    protected processSendMoneyTransfer(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Accepted
     */
    closeAccount(id: string): Promise<void> {
        let url_ = this.baseUrl + "/api/accounts/{id}/close";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCloseAccount(_response);
        });
    }

    protected processCloseAccount(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    queryClients(): Promise<ClientReport[]> {
        let url_ = this.baseUrl + "/odata/Clients";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processQueryClients(_response);
        });
    }

    protected processQueryClients(response: Response): Promise<ClientReport[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClientReport.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result400 = resultData400 !== undefined ? resultData400 : null as any;
    
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport[]>(null as any);
    }

    /**
     * Same as GET /odata/Clients, but for $filter expressions too large/complex for a query string (RFC 10008).
     * @param body (optional) 
     * @return OK
     */
    queryClientsViaQueryMethod(body: Body | undefined): Promise<ClientReport[]> {
        let url_ = this.baseUrl + "/odata/Clients";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "QUERY",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processQueryClientsViaQueryMethod(_response);
        });
    }

    protected processQueryClientsViaQueryMethod(response: Response): Promise<ClientReport[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ClientReport.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result400 = resultData400 !== undefined ? resultData400 : null as any;
    
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ClientReport[]>(null as any);
    }

    streamEvents(): Promise<void> {
        let url_ = this.baseUrl + "/api/events";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamEvents(_response);
        });
    }

    protected processStreamEvents(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result400 = resultData400 !== undefined ? resultData400 : null as any;
    
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class AccountDetailsReport implements IAccountDetailsReport {
    id?: string;
    clientReportId?: string;
    ledgers?: LedgerReport[];
    accountName?: string | undefined;
    balance?: number;
    accountNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IAccountDetailsReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.clientReportId = _data["clientReportId"];
            if (Array.isArray(_data["ledgers"])) {
                this.ledgers = [] as any;
                for (let item of _data["ledgers"])
                    this.ledgers!.push(LedgerReport.fromJS(item));
            }
            this.accountName = _data["accountName"];
            this.balance = _data["balance"];
            this.accountNumber = _data["accountNumber"];
        }
    }

    static fromJS(data: any): AccountDetailsReport {
        data = typeof data === 'object' ? data : {};
        let result = new AccountDetailsReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["clientReportId"] = this.clientReportId;
        if (Array.isArray(this.ledgers)) {
            data["ledgers"] = [];
            for (let item of this.ledgers)
                data["ledgers"].push(item ? item.toJSON() : undefined as any);
        }
        data["accountName"] = this.accountName;
        data["balance"] = this.balance;
        data["accountNumber"] = this.accountNumber;
        return data;
    }
}

export interface IAccountDetailsReport {
    id?: string;
    clientReportId?: string;
    ledgers?: LedgerReport[];
    accountName?: string | undefined;
    balance?: number;
    accountNumber?: string | undefined;

    [key: string]: any;
}

export class AccountReport implements IAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IAccountReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.clientDetailsReportId = _data["clientDetailsReportId"];
            this.accountName = _data["accountName"];
            this.accountNumber = _data["accountNumber"];
        }
    }

    static fromJS(data: any): AccountReport {
        data = typeof data === 'object' ? data : {};
        let result = new AccountReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["clientDetailsReportId"] = this.clientDetailsReportId;
        data["accountName"] = this.accountName;
        data["accountNumber"] = this.accountNumber;
        return data;
    }
}

export interface IAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;
}

export class AssignNewBankCardRequest implements IAssignNewBankCardRequest {
    accountId!: string;

    [key: string]: any;

    constructor(data?: IAssignNewBankCardRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.accountId = _data["accountId"];
        }
    }

    static fromJS(data: any): AssignNewBankCardRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AssignNewBankCardRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["accountId"] = this.accountId;
        return data;
    }
}

export interface IAssignNewBankCardRequest {
    accountId: string;

    [key: string]: any;
}

export class BankCardReport implements IBankCardReport {
    id?: string;
    clientDetailsReportId?: string;
    accountId?: string;
    status?: string | undefined;

    [key: string]: any;

    constructor(data?: IBankCardReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.clientDetailsReportId = _data["clientDetailsReportId"];
            this.accountId = _data["accountId"];
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): BankCardReport {
        data = typeof data === 'object' ? data : {};
        let result = new BankCardReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["clientDetailsReportId"] = this.clientDetailsReportId;
        data["accountId"] = this.accountId;
        data["status"] = this.status;
        return data;
    }
}

export interface IBankCardReport {
    id?: string;
    clientDetailsReportId?: string;
    accountId?: string;
    status?: string | undefined;

    [key: string]: any;
}

export class ChangeAccountNameRequest implements IChangeAccountNameRequest {
    accountName!: string | undefined;

    [key: string]: any;

    constructor(data?: IChangeAccountNameRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.accountName = _data["accountName"];
        }
    }

    static fromJS(data: any): ChangeAccountNameRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ChangeAccountNameRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["accountName"] = this.accountName;
        return data;
    }
}

export interface IChangeAccountNameRequest {
    accountName: string | undefined;

    [key: string]: any;
}

export class ChangeClientNameRequest implements IChangeClientNameRequest {
    clientName!: string | undefined;

    [key: string]: any;

    constructor(data?: IChangeClientNameRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.clientName = _data["clientName"];
        }
    }

    static fromJS(data: any): ChangeClientNameRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ChangeClientNameRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["clientName"] = this.clientName;
        return data;
    }
}

export interface IChangeClientNameRequest {
    clientName: string | undefined;

    [key: string]: any;
}

export class ChangeClientPhoneNumberRequest implements IChangeClientPhoneNumberRequest {
    phoneNumber!: string | undefined;

    [key: string]: any;

    constructor(data?: IChangeClientPhoneNumberRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.phoneNumber = _data["phoneNumber"];
        }
    }

    static fromJS(data: any): ChangeClientPhoneNumberRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ChangeClientPhoneNumberRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["phoneNumber"] = this.phoneNumber;
        return data;
    }
}

export interface IChangeClientPhoneNumberRequest {
    phoneNumber: string | undefined;

    [key: string]: any;
}

export class ClientDetailsReport implements IClientDetailsReport {
    id?: string;
    accounts?: AccountReport[];
    closedAccounts?: ClosedAccountReport[];
    bankCards?: BankCardReport[];
    clientName?: string | undefined;
    street?: string | undefined;
    streetNumber?: string | undefined;
    postalCode?: string | undefined;
    city?: string | undefined;
    phoneNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IClientDetailsReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            if (Array.isArray(_data["accounts"])) {
                this.accounts = [] as any;
                for (let item of _data["accounts"])
                    this.accounts!.push(AccountReport.fromJS(item));
            }
            if (Array.isArray(_data["closedAccounts"])) {
                this.closedAccounts = [] as any;
                for (let item of _data["closedAccounts"])
                    this.closedAccounts!.push(ClosedAccountReport.fromJS(item));
            }
            if (Array.isArray(_data["bankCards"])) {
                this.bankCards = [] as any;
                for (let item of _data["bankCards"])
                    this.bankCards!.push(BankCardReport.fromJS(item));
            }
            this.clientName = _data["clientName"];
            this.street = _data["street"];
            this.streetNumber = _data["streetNumber"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
            this.phoneNumber = _data["phoneNumber"];
        }
    }

    static fromJS(data: any): ClientDetailsReport {
        data = typeof data === 'object' ? data : {};
        let result = new ClientDetailsReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        if (Array.isArray(this.accounts)) {
            data["accounts"] = [];
            for (let item of this.accounts)
                data["accounts"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.closedAccounts)) {
            data["closedAccounts"] = [];
            for (let item of this.closedAccounts)
                data["closedAccounts"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.bankCards)) {
            data["bankCards"] = [];
            for (let item of this.bankCards)
                data["bankCards"].push(item ? item.toJSON() : undefined as any);
        }
        data["clientName"] = this.clientName;
        data["street"] = this.street;
        data["streetNumber"] = this.streetNumber;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        data["phoneNumber"] = this.phoneNumber;
        return data;
    }
}

export interface IClientDetailsReport {
    id?: string;
    accounts?: AccountReport[];
    closedAccounts?: ClosedAccountReport[];
    bankCards?: BankCardReport[];
    clientName?: string | undefined;
    street?: string | undefined;
    streetNumber?: string | undefined;
    postalCode?: string | undefined;
    city?: string | undefined;
    phoneNumber?: string | undefined;

    [key: string]: any;
}

export class ClientIsMovingRequest implements IClientIsMovingRequest {
    street!: string | undefined;
    streetNumber!: string | undefined;
    postalCode!: string | undefined;
    city!: string | undefined;

    [key: string]: any;

    constructor(data?: IClientIsMovingRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.street = _data["street"];
            this.streetNumber = _data["streetNumber"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
        }
    }

    static fromJS(data: any): ClientIsMovingRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ClientIsMovingRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["street"] = this.street;
        data["streetNumber"] = this.streetNumber;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        return data;
    }
}

export interface IClientIsMovingRequest {
    street: string | undefined;
    streetNumber: string | undefined;
    postalCode: string | undefined;
    city: string | undefined;

    [key: string]: any;
}

export class ClientReport implements IClientReport {
    id?: string;
    name?: string | undefined;

    [key: string]: any;

    constructor(data?: IClientReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): ClientReport {
        data = typeof data === 'object' ? data : {};
        let result = new ClientReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["name"] = this.name;
        return data;
    }
}

export interface IClientReport {
    id?: string;
    name?: string | undefined;

    [key: string]: any;
}

export class ClosedAccountReport implements IClosedAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;

    constructor(data?: IClosedAccountReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.clientDetailsReportId = _data["clientDetailsReportId"];
            this.accountName = _data["accountName"];
            this.accountNumber = _data["accountNumber"];
        }
    }

    static fromJS(data: any): ClosedAccountReport {
        data = typeof data === 'object' ? data : {};
        let result = new ClosedAccountReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["clientDetailsReportId"] = this.clientDetailsReportId;
        data["accountName"] = this.accountName;
        data["accountNumber"] = this.accountNumber;
        return data;
    }
}

export interface IClosedAccountReport {
    id?: string;
    clientDetailsReportId?: string;
    accountName?: string | undefined;
    accountNumber?: string | undefined;

    [key: string]: any;
}

export class CreateClientRequest implements ICreateClientRequest {
    clientName!: string | undefined;
    street!: string | undefined;
    streetNumber!: string | undefined;
    postalCode!: string | undefined;
    city!: string | undefined;
    phoneNumber!: string | undefined;

    [key: string]: any;

    constructor(data?: ICreateClientRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.clientName = _data["clientName"];
            this.street = _data["street"];
            this.streetNumber = _data["streetNumber"];
            this.postalCode = _data["postalCode"];
            this.city = _data["city"];
            this.phoneNumber = _data["phoneNumber"];
        }
    }

    static fromJS(data: any): CreateClientRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateClientRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["clientName"] = this.clientName;
        data["street"] = this.street;
        data["streetNumber"] = this.streetNumber;
        data["postalCode"] = this.postalCode;
        data["city"] = this.city;
        data["phoneNumber"] = this.phoneNumber;
        return data;
    }
}

export interface ICreateClientRequest {
    clientName: string | undefined;
    street: string | undefined;
    streetNumber: string | undefined;
    postalCode: string | undefined;
    city: string | undefined;
    phoneNumber: string | undefined;

    [key: string]: any;
}

export class DepositCashRequest implements IDepositCashRequest {
    amount!: number;

    [key: string]: any;

    constructor(data?: IDepositCashRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.amount = _data["amount"];
        }
    }

    static fromJS(data: any): DepositCashRequest {
        data = typeof data === 'object' ? data : {};
        let result = new DepositCashRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["amount"] = this.amount;
        return data;
    }
}

export interface IDepositCashRequest {
    amount: number;

    [key: string]: any;
}

export class LedgerReport implements ILedgerReport {
    id?: string;
    accountDetailsReportId?: string;
    action?: string;
    amount?: number;

    [key: string]: any;

    constructor(data?: ILedgerReport) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.accountDetailsReportId = _data["accountDetailsReportId"];
            this.action = _data["action"];
            this.amount = _data["amount"];
        }
    }

    static fromJS(data: any): LedgerReport {
        data = typeof data === 'object' ? data : {};
        let result = new LedgerReport();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["accountDetailsReportId"] = this.accountDetailsReportId;
        data["action"] = this.action;
        data["amount"] = this.amount;
        return data;
    }
}

export interface ILedgerReport {
    id?: string;
    accountDetailsReportId?: string;
    action?: string;
    amount?: number;

    [key: string]: any;
}

export class OpenNewAccountForClientRequest implements IOpenNewAccountForClientRequest {
    accountName!: string | undefined;

    [key: string]: any;

    constructor(data?: IOpenNewAccountForClientRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.accountName = _data["accountName"];
        }
    }

    static fromJS(data: any): OpenNewAccountForClientRequest {
        data = typeof data === 'object' ? data : {};
        let result = new OpenNewAccountForClientRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["accountName"] = this.accountName;
        return data;
    }
}

export interface IOpenNewAccountForClientRequest {
    accountName: string | undefined;

    [key: string]: any;
}

export class SendMoneyTransferRequest implements ISendMoneyTransferRequest {
    amount!: number;
    accountNumber!: string | undefined;

    [key: string]: any;

    constructor(data?: ISendMoneyTransferRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.amount = _data["amount"];
            this.accountNumber = _data["accountNumber"];
        }
    }

    static fromJS(data: any): SendMoneyTransferRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SendMoneyTransferRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["amount"] = this.amount;
        data["accountNumber"] = this.accountNumber;
        return data;
    }
}

export interface ISendMoneyTransferRequest {
    amount: number;
    accountNumber: string | undefined;

    [key: string]: any;
}

export class WithdrawalCashRequest implements IWithdrawalCashRequest {
    amount!: number;

    [key: string]: any;

    constructor(data?: IWithdrawalCashRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.amount = _data["amount"];
        }
    }

    static fromJS(data: any): WithdrawalCashRequest {
        data = typeof data === 'object' ? data : {};
        let result = new WithdrawalCashRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["amount"] = this.amount;
        return data;
    }
}

export interface IWithdrawalCashRequest {
    amount: number;

    [key: string]: any;
}

export class Body implements IBody {
    /** An OData $filter expression, e.g. "contains(Name, 'Smith')". */
    filter?: string | undefined;

    [key: string]: any;

    constructor(data?: IBody) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.filter = _data["filter"];
        }
    }

    static fromJS(data: any): Body {
        data = typeof data === 'object' ? data : {};
        let result = new Body();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["filter"] = this.filter;
        return data;
    }
}

export interface IBody {
    /** An OData $filter expression, e.g. "contains(Name, 'Smith')". */
    filter?: string | undefined;

    [key: string]: any;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

