// <auto-generated />
using System;
using Fohjin.DDD.Reporting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fohjin.DDD.Reporting.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260813131103_AddReportingNavigationProperties")]
    partial class AddReportingNavigationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.AccountDetailsReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountDetailsReport", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.AccountReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientDetailsReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("InsertionSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsertionSequence"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientDetailsReportId");

                    b.ToTable("AccountReport", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.BankCardReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientDetailsReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("InsertionSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsertionSequence"));

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientDetailsReportId");

                    b.ToTable("BankCardReport", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.ClientDetailsReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientDetailsReport", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.ClientReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientReport", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.LedgerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountDetailsReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("InsertionSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InsertionSequence"));

                    b.HasKey("Id");

                    b.HasIndex("AccountDetailsReportId");

                    b.ToTable("LedgerReport", (string)null);
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.AccountReport", b =>
                {
                    b.HasOne("Fohjin.DDD.Reporting.Dtos.ClientDetailsReport", null)
                        .WithMany("AllAccounts")
                        .HasForeignKey("ClientDetailsReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.BankCardReport", b =>
                {
                    b.HasOne("Fohjin.DDD.Reporting.Dtos.ClientDetailsReport", null)
                        .WithMany("BankCards")
                        .HasForeignKey("ClientDetailsReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.LedgerReport", b =>
                {
                    b.HasOne("Fohjin.DDD.Reporting.Dtos.AccountDetailsReport", null)
                        .WithMany("Ledgers")
                        .HasForeignKey("AccountDetailsReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.AccountDetailsReport", b =>
                {
                    b.Navigation("Ledgers");
                });

            modelBuilder.Entity("Fohjin.DDD.Reporting.Dtos.ClientDetailsReport", b =>
                {
                    b.Navigation("AllAccounts");

                    b.Navigation("BankCards");
                });
#pragma warning restore 612, 618
        }
    }
}
